Layout/LineLength:
  Exclude:
    - test/**/*
  IgnoredPatterns: ['\A\s*# @overload']

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
