Layout/LineLength:
  Exclude:
    - test/**/*
  IgnoredPatterns: ['\A\s*# @overload']

Metrics/AbcSize:
  Exclude:
    - test/**/*
  Max: 16.31
Metrics/ParameterLists:
  CountKeywordArgs: false

Style/Documentation:
  Exclude:
    - test/**/*
