env:
  global:
    - AWS_ACCESS_KEY_ID=key
    - AWS_SECRET_ACCESS_KEY=secret
gemfile:
  - gemfiles/libxml.gemfile
  - gemfiles/nokogiri.gemfile
  - gemfiles/ox.gemfile
  - gemfiles/rexml.gemfile
rvm:
  - 2.0.0
  - 1.9.3
  - 2.1.0
  - jruby-19mode
  - rbx-2
exclude:
  - rvm: jruby-19mode
    gemfile:
      - gemfiles/libxml.gemfile
      - gemfiles/ox.gemfile
