env:
  global:
    - AWS_ACCESS_KEY_ID=key
    - AWS_SECRET_ACCESS_KEY=secret
gemfile:
  - gemfiles/libxml.gemfile
  - gemfiles/nokogiri.gemfile
  - gemfiles/ox.gemfile
  - gemfiles/rexml.gemfile
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.5
  - 2.2.0
  - 2.2.1
  - ruby-head
  - jruby-19mode
  - rbx-2
matrix:
  exclude:
    - rvm: jruby-19mode
      gemfile: gemfiles/libxml.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/ox.gemfile
