name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7]

    container:
      image: ruby:${{ matrix.ruby }}

    steps:
    - uses: actions/checkout@v1

    - name: Run tests
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
